"""
Self-Supervised Distillation: DINOv2 to U-Net
This script reads the highly-accurate PAGE-XML outputs generated by our zero-shot
DINOv2 pipeline and converts them into ground-truth segmentation masks (.npz files)
to train our custom U-Net. 

This enables a completely self-contained, self-supervised workflow without relying
on external OCR models like Kraken.

Mask Channels:
0: Text Region (filled polygons)
1: Text Line Boundary (filled polygons)
2: Baselines (3px thick lines)
"""

import os
import cv2
import argparse
import numpy as np
import shutil
from pathlib import Path
from lxml import etree
from tqdm import tqdm

def parse_coords(coords_str):
    """Parses a PAGE-XML coords string 'x1,y1 x2,y2 ...' into a numpy array of points."""
    pts = []
    for pt_str in coords_str.strip().split():
        if ',' in pt_str:
            x, y = map(float, pt_str.split(','))
            pts.append([int(x), int(y)])
    return np.array(pts, dtype=np.int32)

def generate_mask_from_xml(xml_path):
    """
    Parses a PAGE-XML file and generates a 3-channel numpy mask.
    Returns: (mask, image_filename, img_w, img_h)
    """
    ns = {"p": "http://schema.primaresearch.org/PAGE/gts/pagecontent/2019-07-15"}
    
    try:
        tree = etree.parse(str(xml_path))
    except Exception as e:
        print(f"Error parsing {xml_path}: {e}")
        return None, None, 0, 0
        
    root = tree.getroot()
    page = root.find(".//p:Page", namespaces=ns)
    
    if page is None:
        return None, None, 0, 0
        
    img_filename = page.get("imageFilename")
    img_w = int(page.get("imageWidth"))
    img_h = int(page.get("imageHeight"))
    
    mask0 = np.zeros((img_h, img_w), dtype=np.uint8) # Regions
    mask1 = np.zeros((img_h, img_w), dtype=np.uint8) # Lines
    mask2 = np.zeros((img_h, img_w), dtype=np.uint8) # Baselines
    
    for region in page.findall(".//p:TextRegion", namespaces=ns):
        coords_el = region.find("p:Coords", namespaces=ns)
        if coords_el is not None and coords_el.get("points"):
            pts = parse_coords(coords_el.get("points"))
            if len(pts) >= 3:
                cv2.fillPoly(mask0, [pts], 255)
                
    for line in page.findall(".//p:TextLine", namespaces=ns):
        coords_el = line.find("p:Coords", namespaces=ns)
        if coords_el is not None and coords_el.get("points"):
            pts = parse_coords(coords_el.get("points"))
            if len(pts) >= 3:
                cv2.fillPoly(mask1, [pts], 255)
                
        baseline_el = line.find("p:Baseline", namespaces=ns)
        if baseline_el is not None and baseline_el.get("points"):
            pts = parse_coords(baseline_el.get("points"))
            if len(pts) >= 2:
                cv2.polylines(mask2, [pts], isClosed=False, color=255, thickness=3)
                
    mask = np.stack([mask0, mask1, mask2], axis=-1)
    return mask, img_filename, img_w, img_h

def main():
    parser = argparse.ArgumentParser(description="Convert DINO PAGE-XML to U-Net Training Masks")
    parser.add_argument("--xml_dir", required=True, help="Directory containing DINOv2 XML outputs")
    parser.add_argument("--img_dir", required=True, help="Directory containing original images")
    parser.add_argument("--output_dir", default="training_data", help="Output directory for training dataset")
    args = parser.parse_args()

    xml_dir = Path(args.xml_dir)
    img_dir = Path(args.img_dir)
    out_dir = Path(args.output_dir)
    
    img_out_dir = out_dir / "images"
    mask_out_dir = out_dir / "masks"
    
    img_out_dir.mkdir(parents=True, exist_ok=True)
    mask_out_dir.mkdir(parents=True, exist_ok=True)

    xml_files = list(xml_dir.glob("*.xml"))
    print(f"Found {len(xml_files)} DINO XML files for Knowledge Distillation.")

    success_count = 0
    for xml_path in tqdm(xml_files, desc="Distilling DINO Pseudo-labels"):
        mask, img_filename, w, h = generate_mask_from_xml(xml_path)
        
        if mask is None or img_filename is None:
            continue
            
        src_img_path = img_dir / img_filename
        if not src_img_path.exists():
            matches = list(img_dir.glob(f"{src_img_path.stem}.*"))
            if matches:
                src_img_path = matches[0]
            else:
                print(f"Warning: Could not find source image {img_filename} for {xml_path.name}")
                continue
                
        out_mask_path = mask_out_dir / f"{xml_path.stem}.npz"
        np.savez_compressed(out_mask_path, mask=mask)
        
        out_img_path = img_out_dir / src_img_path.name
        if not out_img_path.exists():
            shutil.copy2(src_img_path, out_img_path)
            
        success_count += 1

    print(f"\nDistillation complete! Successfully generated {success_count} training pairs.")
    print(f"Images saved to: {img_out_dir}")
    print(f"Masks saved to: {mask_out_dir}")

if __name__ == "__main__":
    main()
